INSERT INTO user(NAME,USERNAME,PASSWORD,ENABLED) VALUES('admin','admin','$2a$06$E.SdZMH01CoPDitvvjzDHe.SDQ3RER5oswkdwj.WfOaNNNw4pVJ6u',1);
INSERT INTO user_roles(ROLE,USER_ID) VALUES('ROLE_ADMIN',1);
INSERT INTO category(NAME) VALUES('java');