INSERT INTO user(NAME,USERNAME,PASSWORD,ENABLED) VALUES('engin','engin','sonat',1);
INSERT INTO user_roles(ROLE,USERNAME) VALUES('ROLE_ADMIN','engin');
INSERT INTO category(NAME) VALUES('java');
INSERT INTO post(DATE,TEXT,USER_ID,CATEGORY_ID) VALUES('2015-12-11 13:57:02','deneme','engin','1');
INSERT INTO comment(DATETIME,DEPTH,TEXT,PARENT_ID,POST_ID) VALUES('2015-12-11 13:57:37','0','comment', NULL,'1');
INSERT INTO comment(DATETIME,DEPTH,TEXT,PARENT_ID,POST_ID) VALUES('2015-12-11 13:57:38','1','comment','1','1');
